# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/framefinder',
                'doc_host': 'https://Iseratho.github.io',
                'git_url': 'https://github.com/Iseratho/framefinder',
                'lib_path': 'framefinder'},
  'syms': {'framefinder.core': {'framefinder.core.foo': ('core.html#foo', 'framefinder/core.py')}}}
